
metricPrefix: "Custom Metrics|AppTweak|"
token:  "raNOLwH21L-ULeTCUXlzGHUzmCo"


mobileApplication:
      - applicationId:  "1040475847"
        country:  "de"
        language: "en"
        religion: "ios"
      -
